# Generated by Django 4.0.6 on 2022-07-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_lista_remove_antropometria_n_user_remove_dexa_n_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometria',
            name='nome',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.lista'),
        ),
    ]
