# Generated by Django 4.0.6 on 2022-07-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_alter_antropometria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometria',
            name='nome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.lista'),
        ),
    ]
