# Generated by Django 4.0.6 on 2022-07-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_alter_antropometria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometria',
            name='Pabdomen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='PantebracoD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='PbracoD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='Pcintura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='PcoxaD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='PpernaD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='Pquadril',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='Ptronco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='estatura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.lista'),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
