# Generated by Django 4.0.6 on 2022-07-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_testes_medidas_remove_dexa_nome_remove_testes_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testes_medidas',
            name='estatura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
